// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    Account: typeof import('./src/components/Account.vue')['default']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Contract: typeof import('./src/components/Contract.vue')['default']
    'Contract copy': typeof import('./src/components/Contract copy.vue')['default']
    Currency: typeof import('./src/components/Currency.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MoneyInput: typeof import('./src/components/MoneyInput.vue')['default']
    PayButton: typeof import('./src/components/PayButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharesBalance: typeof import('./src/components/SharesBalance.vue')['default']
    SharesInput: typeof import('./src/components/SharesInput.vue')['default']
    Stake: typeof import('./src/components/Stake.vue')['default']
    UsdtBalance: typeof import('./src/components/UsdtBalance.vue')['default']
    UsdtInput: typeof import('./src/components/UsdtInput.vue')['default']
    'UsdtInput copy': typeof import('./src/components/UsdtInput copy.vue')['default']
    Withdraw: typeof import('./src/components/Withdraw.vue')['default']
  }
}

export {}
