/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ComplexStorageContract } from "./ComplexStorage";
import { ContextContract } from "./Context";
import { ERC20Contract } from "./ERC20";
import { IERC20Contract } from "./IERC20";
import { MigrationsContract } from "./Migrations";
import { SimpleStorageContract } from "./SimpleStorage";
import { TutorialTokenContract } from "./TutorialToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ComplexStorage"): ComplexStorageContract;
      require(name: "Context"): ContextContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "SimpleStorage"): SimpleStorageContract;
      require(name: "TutorialToken"): TutorialTokenContract;
    }
  }
}

export {
  ComplexStorageContract,
  ComplexStorageInstance,
} from "./ComplexStorage";
export { ContextContract, ContextInstance } from "./Context";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { SimpleStorageContract, SimpleStorageInstance } from "./SimpleStorage";
export { TutorialTokenContract, TutorialTokenInstance } from "./TutorialToken";
