/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ComplexStorage } from "./ComplexStorage";
export type { Context } from "./Context";
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { Migrations } from "./Migrations";
export type { SimpleStorage } from "./SimpleStorage";
export type { TutorialToken } from "./TutorialToken";
