/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ComplexStorage extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ComplexStorage;
  clone(): ComplexStorage;
  methods: {
    constuint(): NonPayableTransactionObject<string>;

    deviceDataArray(arg0: number | string | BN): NonPayableTransactionObject<{
      deviceBrand: string;
      deviceYear: string;
      batteryWearLevel: string;
      0: string;
      1: string;
      2: string;
    }>;

    investmentsDeadlineTimeStamp(): NonPayableTransactionObject<string>;

    investmentsLimit(): NonPayableTransactionObject<string>;

    singleDD(): NonPayableTransactionObject<{
      deviceBrand: string;
      deviceYear: string;
      batteryWearLevel: string;
      0: string;
      1: string;
      2: string;
    }>;

    storeduint1(): NonPayableTransactionObject<string>;

    string1(): NonPayableTransactionObject<string>;

    string2(): NonPayableTransactionObject<string>;

    string3(): NonPayableTransactionObject<string>;

    uintarray(arg0: number | string | BN): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
