/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseStrategy } from "./BaseStrategy";
export type { ERC20DforceStrategy } from "./ERC20DforceStrategy";
export type { EquityFund } from "./EquityFund";
export type { IBorrower } from "./IBorrower";
export type { ILender } from "./ILender";
export type { InvestmentVault } from "./InvestmentVault";
export type { Lender } from "./Lender";
export type { SimpleVault } from "./SimpleVault";
export type { USDT } from "./USDT";
