/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Borrowed = ContractEventLog<{
  strategy: string;
  amount: string;
  strategyTotalAssets: string;
  totalDebt: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type ReturnFromStrategy = ContractEventLog<{
  previusBalance: string;
  targetBalance: string;
  requestedAmount: string;
  loss: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;

export interface Lender extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Lender;
  clone(): Lender;
  methods: {
    assets(): NonPayableTransactionObject<string>;

    borrow(amount: number | string | BN): NonPayableTransactionObject<void>;

    creditAvailable(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    setStrategy(strategyAddress: string): NonPayableTransactionObject<void>;

    strategy(): NonPayableTransactionObject<string>;

    totalAssets(): NonPayableTransactionObject<string>;

    totalDebt(): NonPayableTransactionObject<string>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;
  };
  events: {
    Borrowed(cb?: Callback<Borrowed>): EventEmitter;
    Borrowed(options?: EventOptions, cb?: Callback<Borrowed>): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    ReturnFromStrategy(cb?: Callback<ReturnFromStrategy>): EventEmitter;
    ReturnFromStrategy(
      options?: EventOptions,
      cb?: Callback<ReturnFromStrategy>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Borrowed", cb: Callback<Borrowed>): void;
  once(event: "Borrowed", options: EventOptions, cb: Callback<Borrowed>): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "ReturnFromStrategy", cb: Callback<ReturnFromStrategy>): void;
  once(
    event: "ReturnFromStrategy",
    options: EventOptions,
    cb: Callback<ReturnFromStrategy>
  ): void;
}
