name: Build application
on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: # fix for EndBug/add-and-commit
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Build app
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v8
      with: 
        default_author: github_actions
        message: 'Build appliction'